---
title: Sienna Wellness
description: 'A test of Eleventy'
repository:
  username: 'kernvalley'
  project: 'siennawellness.com'
url: 'https://www.siennawellness.com'
viewport: 'width=device-width'
referrer: 'no-referrer'
color-scheme: 'light dark'
og-type: 'website'
base: '/'
manifest: '/webapp.webmanifest'
service_worker: '/service-worker.js'
